# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a86bba0b28d9d8ed28a9fcb90c7b872c981bbb7c5492fdc63184c83245d10b27d47842df59162ba9cb0a82ec6152fefe4d0fb3ca7d3f8f31112622bec02a4a9

test:
  secret_key_base: 652925707fc796f3ef0d2834ac3e1606b33d5bdd7b95e9d874ce0d8b513b255be1724e157a7f29fe27d2a63caa33cfb2797db0be7d057d3cfe6ea3e1225399d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
